#!/bin/bash
 
# File to store timestamps
# Timetsamp in the volume for std rt-Linux containers
TIMESTAMP_FILE="/root/container_volume/times.txt"
# TImestamp for partitioned containers
#TIMESTAMP_FILE="/root/times.txt"

# Check if any of the arguments is "create"
for arg in "$@"; do
    #if [[ "$arg" == "start" ]]; then
        # Read the value from devmem at address 0xFF250000
	#DEV_VALUE=$(devmem 0xFF250000)
	# Save the devmem value with timestamp format to the file
	#echo "$DEV_VALUE - START" >> "$TIMESTAMP_FILE"
        #break
    #fi
    if [[ "$arg" == "create" ]]; then
        # Read the value from devmem at address 0xFF250000
	#DEV_VALUE=$(devmem 0xFF250000)
        #  Or read the current timer value from /proc/timer_list for std rt-Linux containers
	TIMER_VALUE=$(awk '/^now/ {print $3; exit}' /proc/timer_list)
	# Save the devmem or timer value with timestamp format to the file
	#echo "$DEV_VALUE - CREATE" >> "$TIMESTAMP_FILE"
    echo "CREATE - $TIMER_VALUE" >> "$TIMESTAMP_FILE"
	break
    fi
done
 
# Call /usr/bin/runc_vanilla or runphi with all the arguments
/usr/bin/runphi "$@"
# /usr/bin/runc_vanilla "$@"

